### ISSUE TITLE
How do I run this on mac?

### ISSUE THREAD

**Issue by boniaditya** [MattePalte/Verbify-TTS#1]
I ran the steps provided in the instructions and cloned the files in the git repo. 

Now I don't know how to move ahead.

**Comment by lwbt** [comment]
> Now I don't know how to move ahead.

You can't at this early stage of development. When you read through the Linux specific install script, which I did for you, you will notice that it sets up a Systemd Service. Here is the [homepage](https://systemd.io/) with an explanation what it is.

Systemd is not the issue here, it is just what the author chose to implement his nifty helper app since he is using Linux. If he had more time and money available he could improve this initial design and integrate into many different platforms. Competition is fierce though: on Android you can enable the [Select to Speak](https://support.google.com/accessibility/android/answer/7349565?hl=en) feature (I guess something like that is also available on iOS), on [ChromeOS](https://support.google.com/chromebook/answer/9032490?hl=en) you have a similar feature, on Windows and Mac you can install Firefox which has a feature called Narrator which [does the same thing for you when you enter reader mode](https://www.ghacks.net/2016/03/08/narrate-text-to-speech-firefox/) (currently broken in Ubuntu snap package and also in flatpak), then there is the non-free (as in libre) https://www.naturalreaders.com/online service which can sometimes misbehave.

You could dream up a lot of things regarding better integration, but if nobody from the community or the author can implement it due to lack of time, then nothing will happen, I guess. The author is a scientist/student who had a need to develop this app because he needed to read more scientific papers. I guess he is mostly done with development and scratching his own itch.

If you want this app to evolve into more start supporting it, maintainership is often seen as a thankless and time consuming job. I better stop here and let the author speak for himself.

**Comment by MattePalte** [comment]
Hi @boniaditya thanks for the interest. 

As @lwbt said I did not have time yet to provide a simple script for Mac, but I can give you some guidelines on how to make it work:
1. make sure you have python 3
2. create a virtual environment and install the dependencies listed in `requirements.txt`in a folder called `env`. Read these entirely first: https://stackoverflow.com/a/59152879 and https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/#using-requirements-files
3. make sure that the server runs at startup of the Mac. (Read: https://stackoverflow.com/questions/6442364/running-script-upon-login-in-mac-os-x ). You need to create an app which runs the following command line
```bash
#!/bin/bash
cd your-verbify-tts-folder-absolute-path
source env/bin/activate
python3 server.py
```
4. create two other apps with the same approach but with the following two snippets:
```bash
#!/bin/bash
your-verbify-tts-folder-absolute-path/env/bin/python your-verbify-tts-folder-absolute-path/command_read.py
```
```bash
#!/bin/bash
your-verbify-tts-folder-absolute-path/env/bin/python your-verbify-tts-folder-absolute-path/command_stop.py
```
5. connect the two apps to two shortcuts ALT+EST for reading and ALT+END for stop reading (See: https://support.apple.com/guide/mac-help/create-keyboard-shortcuts-for-apps-mchlp2271/mac )

Hoping it can help, 
Cheers,
Matteo

**Comment by MattePalte** [comment]
@boniaditya how is it going with your installation on Mac? Were you able to do that?
Cheers,
Matteo

**Comment by MattePalte** [comment]
Feel free to reopen it, I will close it for the time being.
