### ISSUE TITLE
Installation for Windows?

### ISSUE THREAD

**Issue by aleendev** [MattePalte/Verbify-TTS#4]
I'm really interested on a software like this, especially because it works on all desktop applications (not only browser) and has nice natural-like voices, but I have Windows 11. I know it's early development, but if anyone knows of a workaround in the meanwhile, please let me know :C.

Otherwise if you're an interested on Verbify-TTS as a Windows User like me, please upvote this issue.

Have a great day >:D.

**Comment by andika207** [comment]
same here.
just found this tool on AlternativeTo website
but there's no installer for Windows yet
hopefully it will support WinXP 
Juve Merda ! @MattePalte

**Comment by MattePalte** [comment]
Hi @andika207 and @aleendev for your interest! 

I am excited to tell you that I just release the windows version [here](https://github.com/MattePalte/Verbify-TTS/releases/tag/v.0.0.2). You can follow the updated instruction in the readme. 
Please explicitly uninstall existing python versions and install the version 3.8 since there might be problems with some libraries if you used an advanced version.

I am eager to listen to your feedback! I wish you a happy weekend.
Please spread the voice with your friends if they have Windows, they might be interested as well. ;)

**Comment by andika207** [comment]
> I am eager to listen to your feedback!

where is the executable or portable version for Windows ?

**Comment by MattePalte** [comment]
Hi @andika207 
Please read the README there is a step now which says: `.\INSTALL_WINDOWS.bat`
Follow all the steps carefully making sure you have python 3.8 installed.
Matteo

**Comment by andika207** [comment]
I noticed that file but have no interest in such a prehistoric installation method.
